## 1st Note 

In [2]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [6]:
#creatinf empty array
empty_array_2d = np.empty((3, 4))
print(empty_array_2d)

[[7.07377193e+194 6.96411093e+252 1.17573913e+214 4.70079872e+180]
 [5.54163447e+257 2.43567339e-152 6.02669615e+175 1.17573913e+214]
 [6.16283629e-095 1.94210363e+227 5.03439428e+180 1.48946069e-317]]


In [30]:
import numpy as np
 
full_array_2d = np.full((2, 4), 7)
print(full_array_2d)


[[7 7 7 7]
 [7 7 7 7]]


In [32]:
import numpy as np
 
 
# Create an empty array
empa = np.empty((3, 4), dtype=int)
print("Empty Array")
print(empa)
 
# Create a full array
flla = np.full((3, 3), 55, dtype=int)
print("\n Full Array")
print(flla)


Empty Array
[[0 0 5 0]
 [2 0 1 0]
 [1 0 1 0]]

 Full Array
[[55 55 55]
 [55 55 55]
 [55 55 55]]


In [8]:
#array all eliment zero
arr1=np.zeros(4,dtype=int)
print(arr1)

[0 0 0 0]


In [34]:
import numpy as np
a = np.zeros(3, dtype = int)  
print("Matrix a : \n", a)  
  
b = np.zeros([3, 3], dtype = int)  
print("\nMatrix b : \n", b)

Matrix a : 
 [0 0 0]

Matrix b : 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [10]:
#array all eliment one
arr2 = np.ones(5,dtype=int)
print(arr2)

[1 1 1 1 1]


In [36]:
import numpy as np 
  
array = np.ones(5) 
print(array)
a = np.ones(3, dtype = int)  
print("Matrix a : \n", a)  
  
b = np.ones([3, 3], dtype = int)  
print("\nMatrix b : \n", b) 

[1. 1. 1. 1. 1.]
Matrix a : 
 [1 1 1]

Matrix b : 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [16]:
print(arr1.shape) # Returns a tuple indicating the array dimensions
print(arr1.dtype)  # Shows the data type of the elements in the array
print(arr2.size)  # Total number of elements in the array

(4,)
int32
5


In [12]:
#random number in array
arr3 = np.random.rand(5)
print(arr3)

[0.46873789 0.82939735 0.64114541 0.32371841 0.34467718]


In [14]:
# create a numpy 1d-array
array = np.array([1, 2, 3,
                  0, -1, -2])
 
# find index of max element
# in an array
max_ele_index = np.argmax(array)
 
# find max element in an array
max_ele = array[max_ele_index]
 
# find index of min element
# in an array
min_ele_index = np.argmin(array)
 
# find min element in an array
min_ele = array[min_ele_index]
 
# show the outputs
print("Given Array:", array)
 
print("Max Element:", max_ele)
 
print("Min Element:", min_ele)


Given Array: [ 1  2  3  0 -1 -2]
Max Element: 3
Min Element: -2


In [38]:
import numpy 
  
# create numpy array 
arr = numpy.array([[1, 2, 3, 4, 5], 
                   [6, 7, 8, 9, 10], 
                   [11, 12, 13, 14, 15], 
                   [16, 17, 18, 19, 20] 
                   ]) 
  
# view array 
print(arr) 
  
# check for some lists 
print([1, 2, 3, 4, 5] in arr.tolist()) 
print([16, 17, 20, 19, 18] in arr.tolist()) 
print([3, 2, 5, -4, 5] in arr.tolist()) 
print([11, 12, 13, 14, 16] in arr.tolist()) 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
True
False
False
False


In [18]:
import numpy as np
 
# create a numpy 1d-array
array = np.array([1, 2, 3, 
                  0, -1, -2])
 
# find max element in an array
max_ele = np.amax(array)
 
# find min element in an array
min_ele = np.amin(array)
 
 
# show the outputs
print("Given Array:", array)
 
print("Max Element:", max_ele)
 
print("Min Element:", min_ele)


Given Array: [ 1  2  3  0 -1 -2]
Max Element: 3
Min Element: -2


In [20]:
import numpy 
  
# create numpy array 
arr = numpy.array([[2, 8, 9, 4],  
                   [9, 4, 9, 4], 
                   [4, 5, 9, 7], 
                   [2, 9, 4, 3]]) 
  
# Counting sequence 
output = repr(arr).count("9, 4") 
  
# view output 
print(output) 


4


In [26]:
# create array 
x = np.array([1,2,3,4,5,1,2,1,1,1]) 
print("Original array:") 
print(x) 

print(np.bincount(x))

print("Most frequent value in the above array:") 
print(np.bincount(x).argmax())


Original array:
[1 2 3 4 5 1 2 1 1 1]
[0 5 2 1 1 1]
Most frequent value in the above array:
1


In [28]:
import numpy as np 
  
  
x = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 
print("Original array:") 
print(x) 
  
print("Most frequent value in above array") 
y = np.bincount(x) 
maximum = max(y) 
  
for i in range(len(y)): 
    if y[i] == maximum: 
        print(i, end=" ") 

Original array:
[1 1 1 2 3 4 2 4 3 3]
Most frequent value in above array
1 3 

## 2nd Note

In [44]:
import numpy as np  
# creating array  
arr = np.array([2, 4, 6, 8, 10])  
# creating view  
v = arr.view()  
# both arr and v have different id  
print("id of arr", id(arr))  
print("id of v", id(v))  
# changing original array  
# will effect view  
arr[0] = 12
# printing array and view  
print("original array- ", arr)  
print("view- ", v)

id of arr 2871719242672
id of v 2871719245072
original array-  [12  4  6  8 10]
view-  [12  4  6  8 10]


In [62]:
import numpy as np 
  
# creating array 
arr = np.array([2, 4, 6, 8, 10]) 
  
# creating copy of array 
c = arr.copy() 
  
# both arr and c have different id 
print("id of arr", id(arr)) 
print("id of c", id(c)) 
  
# changing original array 
# this will not effect copy 
arr[0] = 12
# c[0]=10
  
# printing array and copy 
print("original array- ", arr) 
print("copy- ", c)

id of arr 2871719247376
id of c 2871719246704
original array-  [12  4  6  8 10]
copy-  [ 2  4  6  8 10]


In [56]:
import numpy as np 
  
# creating array 
arr = np.array([2, 4, 6, 8, 10]) 
  
# assigning arr to nc 
nc = arr 
  
# both arr and nc have same id 
print("id of arr", id(arr)) 
print("id of nc", id(nc)) 
  
# updating nc 
nc[0]= 12

#updating arr
# arr[0]=10
  
# printing the values 
print("original array- ", arr) 
print("assigned array- ", nc) 


id of arr 2871719246992
id of nc 2871719246992
original array-  [ 2  4  6  8 10]
assigned array-  [ 2  4  6  8 10]


In [66]:
# importing the module
import numpy as np
 
# creating an array
arr = np.array([1, 8, 3, 3, 5])
print('Original Array : ', arr)
 
# appending to the array
arr = np.append(arr, [7,8,9])
print('Array after appending : ', arr)


Original Array :  [1 8 3 3 5]
Array after appending :  [1 8 3 3 5 7 8 9]


In [74]:
import numpy as np

#creating a 1st array
arr1 = np.array([1,2,3,4])
print('First array is : ', arr1)

#creating second array
arr2= np.array([4,5,6])
print('Second array is : ', arr2)

# appending arr2 to arr1
arr3 = np.append(arr1,arr2)
print('Array after appending : ', arr)

First array is :  [1 2 3 4]
Second array is :  [4 5 6]
Array after appending :  [1 8 3 3 5 7 8 9]


In [112]:
#concar 2 array with different dims
arr1 = np.array([[1,2,3],[4,5,6]])
print("1st array",arr1)
print("shape of array",arr1.shape)

arr2 = np.array([[7,8,9]])
print("1st array",arr2)
print("shape of array",arr2.shape)

arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)
print("Shape of array",arr3.shape)

1st array [[1 2 3]
 [4 5 6]]
shape of array (2, 3)
1st array [[7 8 9]]
shape of array (1, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of array (3, 3)


In [114]:
# importing the module
import numpy as np
 
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
 
combined = np.concatenate((arr1, arr2), axis=0)
print(combined)


[[1 2]
 [3 4]
 [5 6]]


## 3rd Note

In [129]:
import numpy as np

# initializing matrices 
x = np.array([[1, 3], [4, 5]]) 
y = np.array([[7, 5], [9, 9]]) 

print("Matrix x ",x)
print("Matrix y ",y)
# using add() to add matrices 
print ("The element wise addition of matrix is : ") 
print (np.add(x,y))

# using subtract() to subtract matrices 
print ("The element wise subtraction of matrix is : ") 
print (np.subtract(x,y))

# using divide() to divide matrices 
print ("The element wise division of matrix is : ") 
print (np.divide(x,y))

# using multiply() to multiply matrices element wise 
print ("The element wise multiplication of matrix is : ") 
print (numpy.multiply(x,y)) 

# using dot() to multiply matrices 
print ("The product of matrices is : ") 
print (numpy.dot(x,y))

Matrix x  [[1 3]
 [4 5]]
Matrix y  [[7 5]
 [9 9]]
The element wise addition of matrix is : 
[[ 8  8]
 [13 14]]
The element wise subtraction of matrix is : 
[[-6 -2]
 [-5 -4]]
The element wise division of matrix is : 
[[0.14285714 0.6       ]
 [0.44444444 0.55555556]]
The element wise multiplication of matrix is : 
[[ 7 15]
 [36 45]]
The product of matrices is : 
[[34 32]
 [73 65]]
